### ISSUE TITLE
defsyms missing error

### ISSUE THREAD

**Issue by LexCutch** [Seteeri/construct#2]
`run.sh`
 produces
```
[T-render.l:1] !? (load (path "@lib/defsyms/defsyms.l"))
"/usr/lib/picolisp/lib/defsyms/defsyms.l" -- Open error: No such file or directory

"launcher bye"
```

**Comment by Seteeri** [comment]
That was an unreleased experimental library I was using to manage loading dependencies similar to virtual environments/package managers. 

Construct is almost done with basic functionality so hopefully within the next month or so, I'll finish writing complete instructions and documentation.
